// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv8s0BuJmwVPrO75-k64aDKuGg8UQtqaU',
    appId: '1:621525587953:web:740aa3aa779411c8895650',
    messagingSenderId: '621525587953',
    projectId: 'speeddelivery-d96f7',
    authDomain: 'speeddelivery-d96f7.firebaseapp.com',
    storageBucket: 'speeddelivery-d96f7.firebasestorage.app',
    measurementId: 'G-N3KVGEW2J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPf7djqJjXiOBs8kgWQtdZ13oSIyEM3fU',
    appId: '1:621525587953:android:9a45d56290de7ba0895650',
    messagingSenderId: '621525587953',
    projectId: 'speeddelivery-d96f7',
    storageBucket: 'speeddelivery-d96f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADu3CngnNtgRpCfWZneDthykD-_vn7ZQI',
    appId: '1:621525587953:ios:622d00c3f43a3fad895650',
    messagingSenderId: '621525587953',
    projectId: 'speeddelivery-d96f7',
    storageBucket: 'speeddelivery-d96f7.firebasestorage.app',
    iosClientId: '621525587953-ahucq9kva3ft7fl5opuiqclla882chf1.apps.googleusercontent.com',
    iosBundleId: 'com.opuslabworks.SpeedDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv8s0BuJmwVPrO75-k64aDKuGg8UQtqaU',
    appId: '1:621525587953:web:4f9bc95a1ff5b61e895650',
    messagingSenderId: '621525587953',
    projectId: 'speeddelivery-d96f7',
    authDomain: 'speeddelivery-d96f7.firebaseapp.com',
    storageBucket: 'speeddelivery-d96f7.firebasestorage.app',
    measurementId: 'G-GX6L6HYY4W',
  );
}
